<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RestoreAdditionalProjectSources>$(MSBuildThisFileDirectory)..\..\artifacts</RestoreAdditionalProjectSources>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SearchPulse.Umbraco" Version="0.1.0-alpha.2" />
  </ItemGroup>
</Project>
